import "./env";
import { getSupabaseAdmin } from "../lib/supabase";

// Populates book_samples with one staff_teaser row per book.
//
// IMPORTANT: these are placeholder rows only. Real inventory requires
// publisher-authorized excerpts (sample_type = 'licensed_excerpt' or
// 'publisher_preview_url', with rights_verified_by/rights_verified_at set by
// staff) before this store can launch. The catalog in this dataset is
// synthetic/fictional, so there is no real publisher content to license —
// these teasers are short, original text derived from each book's own
// `description` field, written for this seed script, not generated by the
// live chatbot (which never writes excerpt text — see CLAUDE.md rule 2).
const TEASERS: Record<number, string> = {
  1: "Three neighbors, one overgrown garden, and a block with more history than anyone remembers. The Lanterns of Bellweather starts with a shared shovel and ends up somewhere much bigger.",
  2: "It starts with a donated first edition and a note nobody was supposed to find. Midnight at Archer Pier follows a bookseller pulled into a decades-old coastal mystery, one page at a time.",
  3: "Late trains, lit windows, small kindnesses easy to miss. Small Hours, Bright City is a poetry collection built from the quiet hours of an ordinary city night.",
  4: "No yard, no problem. The Practical Balcony Garden walks beginners through choosing containers, herbs, and vegetables that actually thrive in a small urban space.",
  5: "Look up. Cloud Atlas for Beginners is an illustrated starting point for identifying clouds, reading weather patterns, and keeping your own simple sky journal.",
  6: "Two teens, one shared notebook, and a mission to map every quiet corner of a noisy city. A Map of Quiet Places is a coming-of-age story about finding stillness where you least expect it.",
  7: "Flour on the counter, something rising by the window. Bread on Sunday collects approachable breads, spreads, and the kind of weekend baking rituals worth repeating.",
  8: "After the last visitor leaves and the doors lock, the exhibits start to stir. When the Museum Sleeps is an illustrated story about what a museum gets up to after hours.",
};

async function main() {
  const supabase = getSupabaseAdmin();
  const { data: books, error } = await supabase.from("books").select("id, title");
  if (error) {
    console.error("Failed to load books:\n", error);
    process.exit(1);
  }

  const rows = (books ?? [])
    .filter((b) => TEASERS[b.id as number])
    .map((b) => {
      const excerpt_text = TEASERS[b.id as number];
      return {
        book_id: b.id,
        sample_type: "staff_teaser" as const,
        excerpt_text,
        word_count: excerpt_text.split(/\s+/).length,
        rights_source: "staff-written",
        is_active: true,
      };
    });

  if (rows.length === 0) {
    console.log("No matching books found — run `npm run seed` first.");
    return;
  }

  const { error: insertError } = await supabase.from("book_samples").insert(rows);
  if (insertError) {
    console.error("Failed to seed book_samples:\n", insertError);
    process.exit(1);
  }
  console.log(`Seeded ${rows.length} staff_teaser rows into book_samples.`);
}

main();
